document.write('<ul id="main_menu">');
document.write('<li class="bold_underline">Trochę informacji</li>');
document.write('<li><a href="plan_lekcji.html">Plan lekcji</a></li>');
document.write('<li><a href="dzwonki.html">Dzwonki</a></li>');
document.write('<li><a href="uczniowie.html">Lista uczniów</a></li>');
document.write('<li><a href="nauczyciele.html">Lista nauczycieli</a></li>');
document.write('<li><a href="kalendarz.html">Kalendarz na rok szkolny 2010/2011</a></li>');
document.write('<li><a href="autobusy.html">Autobusy</a></li>');
//document.write('<li><a href="plan_budy.html">Plan budy</a></li>');
document.write('<li class="bold_underline">Trochę rozrywki</li>');
document.write('<li><a href="downloads.html">Downloads</a></li>');
document.write('<li><a href="linki.html">Linki</a></li>');
document.write('<li><a href="dowcipy.html">Dowcipy</a></li>');
document.write('<li><a href="muza.html">Muza</a></li>');
document.write('<li><a href="filmy.html">Filmiki</a></li>');
document.write('<li><a href="mapy.html">Mapy</a></li>');
document.write('<li><a href="gry.html">Gry</a></li>');
document.write('</ul>');